// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoRPddVrzDtCy8udqYTy2Vnmv9V_gx5NE',
    appId: '1:726572948666:web:437c8b3f590bbd57477683',
    messagingSenderId: '726572948666',
    projectId: 'pushnotificationexample-a5ae2',
    authDomain: 'pushnotificationexample-a5ae2.firebaseapp.com',
    storageBucket: 'pushnotificationexample-a5ae2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARdy9b9G2Mtjt2wRXiIxCWSGVFpWluQns',
    appId: '1:726572948666:android:d0a156705cc7322f477683',
    messagingSenderId: '726572948666',
    projectId: 'pushnotificationexample-a5ae2',
    storageBucket: 'pushnotificationexample-a5ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyWLmvhHBWR-S2mukrGbND_cFppxgKMk',
    appId: '1:726572948666:ios:729ad612b284d803477683',
    messagingSenderId: '726572948666',
    projectId: 'pushnotificationexample-a5ae2',
    storageBucket: 'pushnotificationexample-a5ae2.appspot.com',
    iosBundleId: 'com.example.salesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUyWLmvhHBWR-S2mukrGbND_cFppxgKMk',
    appId: '1:726572948666:ios:729ad612b284d803477683',
    messagingSenderId: '726572948666',
    projectId: 'pushnotificationexample-a5ae2',
    storageBucket: 'pushnotificationexample-a5ae2.appspot.com',
    iosBundleId: 'com.example.salesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoRPddVrzDtCy8udqYTy2Vnmv9V_gx5NE',
    appId: '1:726572948666:web:db76f3492f333d45477683',
    messagingSenderId: '726572948666',
    projectId: 'pushnotificationexample-a5ae2',
    authDomain: 'pushnotificationexample-a5ae2.firebaseapp.com',
    storageBucket: 'pushnotificationexample-a5ae2.appspot.com',
  );
}
